package com.database.mybatis.mapper;

import com.database.mybatis.po.Orderinfo;
import com.database.mybatis.po.OrderinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderinfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderinfo
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	long countByExample(OrderinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderinfo
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int deleteByExample(OrderinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderinfo
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int deleteByPrimaryKey(Integer infoid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderinfo
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int insert(Orderinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderinfo
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int insertSelective(Orderinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderinfo
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	List<Orderinfo> selectByExample(OrderinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderinfo
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	Orderinfo selectByPrimaryKey(Integer infoid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderinfo
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Orderinfo record, @Param("example") OrderinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderinfo
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int updateByExample(@Param("record") Orderinfo record, @Param("example") OrderinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderinfo
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int updateByPrimaryKeySelective(Orderinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderinfo
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int updateByPrimaryKey(Orderinfo record);
}