package com.database.mybatis.po;

import java.util.ArrayList;
import java.util.List;

public class NewspaperExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public NewspaperExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andNewsidIsNull() {
			addCriterion("newsid is null");
			return (Criteria) this;
		}

		public Criteria andNewsidIsNotNull() {
			addCriterion("newsid is not null");
			return (Criteria) this;
		}

		public Criteria andNewsidEqualTo(Integer value) {
			addCriterion("newsid =", value, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsidNotEqualTo(Integer value) {
			addCriterion("newsid <>", value, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsidGreaterThan(Integer value) {
			addCriterion("newsid >", value, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsidGreaterThanOrEqualTo(Integer value) {
			addCriterion("newsid >=", value, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsidLessThan(Integer value) {
			addCriterion("newsid <", value, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsidLessThanOrEqualTo(Integer value) {
			addCriterion("newsid <=", value, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsidIn(List<Integer> values) {
			addCriterion("newsid in", values, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsidNotIn(List<Integer> values) {
			addCriterion("newsid not in", values, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsidBetween(Integer value1, Integer value2) {
			addCriterion("newsid between", value1, value2, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsidNotBetween(Integer value1, Integer value2) {
			addCriterion("newsid not between", value1, value2, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsnumIsNull() {
			addCriterion("newsnum is null");
			return (Criteria) this;
		}

		public Criteria andNewsnumIsNotNull() {
			addCriterion("newsnum is not null");
			return (Criteria) this;
		}

		public Criteria andNewsnumEqualTo(Integer value) {
			addCriterion("newsnum =", value, "newsnum");
			return (Criteria) this;
		}

		public Criteria andNewsnumNotEqualTo(Integer value) {
			addCriterion("newsnum <>", value, "newsnum");
			return (Criteria) this;
		}

		public Criteria andNewsnumGreaterThan(Integer value) {
			addCriterion("newsnum >", value, "newsnum");
			return (Criteria) this;
		}

		public Criteria andNewsnumGreaterThanOrEqualTo(Integer value) {
			addCriterion("newsnum >=", value, "newsnum");
			return (Criteria) this;
		}

		public Criteria andNewsnumLessThan(Integer value) {
			addCriterion("newsnum <", value, "newsnum");
			return (Criteria) this;
		}

		public Criteria andNewsnumLessThanOrEqualTo(Integer value) {
			addCriterion("newsnum <=", value, "newsnum");
			return (Criteria) this;
		}

		public Criteria andNewsnumIn(List<Integer> values) {
			addCriterion("newsnum in", values, "newsnum");
			return (Criteria) this;
		}

		public Criteria andNewsnumNotIn(List<Integer> values) {
			addCriterion("newsnum not in", values, "newsnum");
			return (Criteria) this;
		}

		public Criteria andNewsnumBetween(Integer value1, Integer value2) {
			addCriterion("newsnum between", value1, value2, "newsnum");
			return (Criteria) this;
		}

		public Criteria andNewsnumNotBetween(Integer value1, Integer value2) {
			addCriterion("newsnum not between", value1, value2, "newsnum");
			return (Criteria) this;
		}

		public Criteria andNewsnameIsNull() {
			addCriterion("newsname is null");
			return (Criteria) this;
		}

		public Criteria andNewsnameIsNotNull() {
			addCriterion("newsname is not null");
			return (Criteria) this;
		}

		public Criteria andNewsnameEqualTo(String value) {
			addCriterion("newsname =", value, "newsname");
			return (Criteria) this;
		}

		public Criteria andNewsnameNotEqualTo(String value) {
			addCriterion("newsname <>", value, "newsname");
			return (Criteria) this;
		}

		public Criteria andNewsnameGreaterThan(String value) {
			addCriterion("newsname >", value, "newsname");
			return (Criteria) this;
		}

		public Criteria andNewsnameGreaterThanOrEqualTo(String value) {
			addCriterion("newsname >=", value, "newsname");
			return (Criteria) this;
		}

		public Criteria andNewsnameLessThan(String value) {
			addCriterion("newsname <", value, "newsname");
			return (Criteria) this;
		}

		public Criteria andNewsnameLessThanOrEqualTo(String value) {
			addCriterion("newsname <=", value, "newsname");
			return (Criteria) this;
		}

		public Criteria andNewsnameLike(String value) {
			addCriterion("newsname like", value, "newsname");
			return (Criteria) this;
		}

		public Criteria andNewsnameNotLike(String value) {
			addCriterion("newsname not like", value, "newsname");
			return (Criteria) this;
		}

		public Criteria andNewsnameIn(List<String> values) {
			addCriterion("newsname in", values, "newsname");
			return (Criteria) this;
		}

		public Criteria andNewsnameNotIn(List<String> values) {
			addCriterion("newsname not in", values, "newsname");
			return (Criteria) this;
		}

		public Criteria andNewsnameBetween(String value1, String value2) {
			addCriterion("newsname between", value1, value2, "newsname");
			return (Criteria) this;
		}

		public Criteria andNewsnameNotBetween(String value1, String value2) {
			addCriterion("newsname not between", value1, value2, "newsname");
			return (Criteria) this;
		}

		public Criteria andNewsclassIsNull() {
			addCriterion("newsclass is null");
			return (Criteria) this;
		}

		public Criteria andNewsclassIsNotNull() {
			addCriterion("newsclass is not null");
			return (Criteria) this;
		}

		public Criteria andNewsclassEqualTo(Integer value) {
			addCriterion("newsclass =", value, "newsclass");
			return (Criteria) this;
		}

		public Criteria andNewsclassNotEqualTo(Integer value) {
			addCriterion("newsclass <>", value, "newsclass");
			return (Criteria) this;
		}

		public Criteria andNewsclassGreaterThan(Integer value) {
			addCriterion("newsclass >", value, "newsclass");
			return (Criteria) this;
		}

		public Criteria andNewsclassGreaterThanOrEqualTo(Integer value) {
			addCriterion("newsclass >=", value, "newsclass");
			return (Criteria) this;
		}

		public Criteria andNewsclassLessThan(Integer value) {
			addCriterion("newsclass <", value, "newsclass");
			return (Criteria) this;
		}

		public Criteria andNewsclassLessThanOrEqualTo(Integer value) {
			addCriterion("newsclass <=", value, "newsclass");
			return (Criteria) this;
		}

		public Criteria andNewsclassIn(List<Integer> values) {
			addCriterion("newsclass in", values, "newsclass");
			return (Criteria) this;
		}

		public Criteria andNewsclassNotIn(List<Integer> values) {
			addCriterion("newsclass not in", values, "newsclass");
			return (Criteria) this;
		}

		public Criteria andNewsclassBetween(Integer value1, Integer value2) {
			addCriterion("newsclass between", value1, value2, "newsclass");
			return (Criteria) this;
		}

		public Criteria andNewsclassNotBetween(Integer value1, Integer value2) {
			addCriterion("newsclass not between", value1, value2, "newsclass");
			return (Criteria) this;
		}

		public Criteria andPressIsNull() {
			addCriterion("press is null");
			return (Criteria) this;
		}

		public Criteria andPressIsNotNull() {
			addCriterion("press is not null");
			return (Criteria) this;
		}

		public Criteria andPressEqualTo(String value) {
			addCriterion("press =", value, "press");
			return (Criteria) this;
		}

		public Criteria andPressNotEqualTo(String value) {
			addCriterion("press <>", value, "press");
			return (Criteria) this;
		}

		public Criteria andPressGreaterThan(String value) {
			addCriterion("press >", value, "press");
			return (Criteria) this;
		}

		public Criteria andPressGreaterThanOrEqualTo(String value) {
			addCriterion("press >=", value, "press");
			return (Criteria) this;
		}

		public Criteria andPressLessThan(String value) {
			addCriterion("press <", value, "press");
			return (Criteria) this;
		}

		public Criteria andPressLessThanOrEqualTo(String value) {
			addCriterion("press <=", value, "press");
			return (Criteria) this;
		}

		public Criteria andPressLike(String value) {
			addCriterion("press like", value, "press");
			return (Criteria) this;
		}

		public Criteria andPressNotLike(String value) {
			addCriterion("press not like", value, "press");
			return (Criteria) this;
		}

		public Criteria andPressIn(List<String> values) {
			addCriterion("press in", values, "press");
			return (Criteria) this;
		}

		public Criteria andPressNotIn(List<String> values) {
			addCriterion("press not in", values, "press");
			return (Criteria) this;
		}

		public Criteria andPressBetween(String value1, String value2) {
			addCriterion("press between", value1, value2, "press");
			return (Criteria) this;
		}

		public Criteria andPressNotBetween(String value1, String value2) {
			addCriterion("press not between", value1, value2, "press");
			return (Criteria) this;
		}

		public Criteria andPublishIsNull() {
			addCriterion("publish is null");
			return (Criteria) this;
		}

		public Criteria andPublishIsNotNull() {
			addCriterion("publish is not null");
			return (Criteria) this;
		}

		public Criteria andPublishEqualTo(String value) {
			addCriterion("publish =", value, "publish");
			return (Criteria) this;
		}

		public Criteria andPublishNotEqualTo(String value) {
			addCriterion("publish <>", value, "publish");
			return (Criteria) this;
		}

		public Criteria andPublishGreaterThan(String value) {
			addCriterion("publish >", value, "publish");
			return (Criteria) this;
		}

		public Criteria andPublishGreaterThanOrEqualTo(String value) {
			addCriterion("publish >=", value, "publish");
			return (Criteria) this;
		}

		public Criteria andPublishLessThan(String value) {
			addCriterion("publish <", value, "publish");
			return (Criteria) this;
		}

		public Criteria andPublishLessThanOrEqualTo(String value) {
			addCriterion("publish <=", value, "publish");
			return (Criteria) this;
		}

		public Criteria andPublishLike(String value) {
			addCriterion("publish like", value, "publish");
			return (Criteria) this;
		}

		public Criteria andPublishNotLike(String value) {
			addCriterion("publish not like", value, "publish");
			return (Criteria) this;
		}

		public Criteria andPublishIn(List<String> values) {
			addCriterion("publish in", values, "publish");
			return (Criteria) this;
		}

		public Criteria andPublishNotIn(List<String> values) {
			addCriterion("publish not in", values, "publish");
			return (Criteria) this;
		}

		public Criteria andPublishBetween(String value1, String value2) {
			addCriterion("publish between", value1, value2, "publish");
			return (Criteria) this;
		}

		public Criteria andPublishNotBetween(String value1, String value2) {
			addCriterion("publish not between", value1, value2, "publish");
			return (Criteria) this;
		}

		public Criteria andQuarterlyIsNull() {
			addCriterion("quarterly is null");
			return (Criteria) this;
		}

		public Criteria andQuarterlyIsNotNull() {
			addCriterion("quarterly is not null");
			return (Criteria) this;
		}

		public Criteria andQuarterlyEqualTo(Float value) {
			addCriterion("quarterly =", value, "quarterly");
			return (Criteria) this;
		}

		public Criteria andQuarterlyNotEqualTo(Float value) {
			addCriterion("quarterly <>", value, "quarterly");
			return (Criteria) this;
		}

		public Criteria andQuarterlyGreaterThan(Float value) {
			addCriterion("quarterly >", value, "quarterly");
			return (Criteria) this;
		}

		public Criteria andQuarterlyGreaterThanOrEqualTo(Float value) {
			addCriterion("quarterly >=", value, "quarterly");
			return (Criteria) this;
		}

		public Criteria andQuarterlyLessThan(Float value) {
			addCriterion("quarterly <", value, "quarterly");
			return (Criteria) this;
		}

		public Criteria andQuarterlyLessThanOrEqualTo(Float value) {
			addCriterion("quarterly <=", value, "quarterly");
			return (Criteria) this;
		}

		public Criteria andQuarterlyIn(List<Float> values) {
			addCriterion("quarterly in", values, "quarterly");
			return (Criteria) this;
		}

		public Criteria andQuarterlyNotIn(List<Float> values) {
			addCriterion("quarterly not in", values, "quarterly");
			return (Criteria) this;
		}

		public Criteria andQuarterlyBetween(Float value1, Float value2) {
			addCriterion("quarterly between", value1, value2, "quarterly");
			return (Criteria) this;
		}

		public Criteria andQuarterlyNotBetween(Float value1, Float value2) {
			addCriterion("quarterly not between", value1, value2, "quarterly");
			return (Criteria) this;
		}

		public Criteria andPiclocationIsNull() {
			addCriterion("piclocation is null");
			return (Criteria) this;
		}

		public Criteria andPiclocationIsNotNull() {
			addCriterion("piclocation is not null");
			return (Criteria) this;
		}

		public Criteria andPiclocationEqualTo(String value) {
			addCriterion("piclocation =", value, "piclocation");
			return (Criteria) this;
		}

		public Criteria andPiclocationNotEqualTo(String value) {
			addCriterion("piclocation <>", value, "piclocation");
			return (Criteria) this;
		}

		public Criteria andPiclocationGreaterThan(String value) {
			addCriterion("piclocation >", value, "piclocation");
			return (Criteria) this;
		}

		public Criteria andPiclocationGreaterThanOrEqualTo(String value) {
			addCriterion("piclocation >=", value, "piclocation");
			return (Criteria) this;
		}

		public Criteria andPiclocationLessThan(String value) {
			addCriterion("piclocation <", value, "piclocation");
			return (Criteria) this;
		}

		public Criteria andPiclocationLessThanOrEqualTo(String value) {
			addCriterion("piclocation <=", value, "piclocation");
			return (Criteria) this;
		}

		public Criteria andPiclocationLike(String value) {
			addCriterion("piclocation like", value, "piclocation");
			return (Criteria) this;
		}

		public Criteria andPiclocationNotLike(String value) {
			addCriterion("piclocation not like", value, "piclocation");
			return (Criteria) this;
		}

		public Criteria andPiclocationIn(List<String> values) {
			addCriterion("piclocation in", values, "piclocation");
			return (Criteria) this;
		}

		public Criteria andPiclocationNotIn(List<String> values) {
			addCriterion("piclocation not in", values, "piclocation");
			return (Criteria) this;
		}

		public Criteria andPiclocationBetween(String value1, String value2) {
			addCriterion("piclocation between", value1, value2, "piclocation");
			return (Criteria) this;
		}

		public Criteria andPiclocationNotBetween(String value1, String value2) {
			addCriterion("piclocation not between", value1, value2, "piclocation");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table newspaper
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 17 23:12:21 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}