package com.database.mybatis.po;

public class Newspaper {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newspaper.newsid
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private Integer newsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newspaper.newsnum
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private Integer newsnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newspaper.newsname
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private String newsname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newspaper.newsclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private Integer newsclass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newspaper.press
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private String press;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newspaper.publish
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private String publish;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newspaper.quarterly
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private Float quarterly;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newspaper.piclocation
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private String piclocation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newspaper.content
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newspaper.newsid
	 * @return  the value of newspaper.newsid
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public Integer getNewsid() {
		return newsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newspaper.newsid
	 * @param newsid  the value for newspaper.newsid
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setNewsid(Integer newsid) {
		this.newsid = newsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newspaper.newsnum
	 * @return  the value of newspaper.newsnum
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public Integer getNewsnum() {
		return newsnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newspaper.newsnum
	 * @param newsnum  the value for newspaper.newsnum
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setNewsnum(Integer newsnum) {
		this.newsnum = newsnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newspaper.newsname
	 * @return  the value of newspaper.newsname
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public String getNewsname() {
		return newsname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newspaper.newsname
	 * @param newsname  the value for newspaper.newsname
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setNewsname(String newsname) {
		this.newsname = newsname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newspaper.newsclass
	 * @return  the value of newspaper.newsclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public Integer getNewsclass() {
		return newsclass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newspaper.newsclass
	 * @param newsclass  the value for newspaper.newsclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setNewsclass(Integer newsclass) {
		this.newsclass = newsclass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newspaper.press
	 * @return  the value of newspaper.press
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public String getPress() {
		return press;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newspaper.press
	 * @param press  the value for newspaper.press
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setPress(String press) {
		this.press = press;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newspaper.publish
	 * @return  the value of newspaper.publish
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public String getPublish() {
		return publish;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newspaper.publish
	 * @param publish  the value for newspaper.publish
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setPublish(String publish) {
		this.publish = publish;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newspaper.quarterly
	 * @return  the value of newspaper.quarterly
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public Float getQuarterly() {
		return quarterly;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newspaper.quarterly
	 * @param quarterly  the value for newspaper.quarterly
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setQuarterly(Float quarterly) {
		this.quarterly = quarterly;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newspaper.piclocation
	 * @return  the value of newspaper.piclocation
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public String getPiclocation() {
		return piclocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newspaper.piclocation
	 * @param piclocation  the value for newspaper.piclocation
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setPiclocation(String piclocation) {
		this.piclocation = piclocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newspaper.content
	 * @return  the value of newspaper.content
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newspaper.content
	 * @param content  the value for newspaper.content
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}
}