package com.database.mybatis.po;

public class Orderinfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderinfo.infoid
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private Integer infoid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderinfo.orderid
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private String orderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderinfo.newsid
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private Integer newsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderinfo.ordernum
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private Integer ordernum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderinfo.ordermouth
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private Integer ordermouth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderinfo.price
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private Float price;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderinfo.infoid
	 * @return  the value of orderinfo.infoid
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public Integer getInfoid() {
		return infoid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderinfo.infoid
	 * @param infoid  the value for orderinfo.infoid
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setInfoid(Integer infoid) {
		this.infoid = infoid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderinfo.orderid
	 * @return  the value of orderinfo.orderid
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public String getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderinfo.orderid
	 * @param orderid  the value for orderinfo.orderid
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderinfo.newsid
	 * @return  the value of orderinfo.newsid
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public Integer getNewsid() {
		return newsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderinfo.newsid
	 * @param newsid  the value for orderinfo.newsid
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setNewsid(Integer newsid) {
		this.newsid = newsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderinfo.ordernum
	 * @return  the value of orderinfo.ordernum
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public Integer getOrdernum() {
		return ordernum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderinfo.ordernum
	 * @param ordernum  the value for orderinfo.ordernum
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setOrdernum(Integer ordernum) {
		this.ordernum = ordernum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderinfo.ordermouth
	 * @return  the value of orderinfo.ordermouth
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public Integer getOrdermouth() {
		return ordermouth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderinfo.ordermouth
	 * @param ordermouth  the value for orderinfo.ordermouth
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setOrdermouth(Integer ordermouth) {
		this.ordermouth = ordermouth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderinfo.price
	 * @return  the value of orderinfo.price
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public Float getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderinfo.price
	 * @param price  the value for orderinfo.price
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setPrice(Float price) {
		this.price = price;
	}
}