package com.database.mybatis.po;

public class Orderall {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderall.orderid
     *
     * @mbg.generated Tue Jun 20 22:36:47 CST 2017
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderall.userid
     *
     * @mbg.generated Tue Jun 20 22:36:47 CST 2017
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderall.allprice
     *
     * @mbg.generated Tue Jun 20 22:36:47 CST 2017
     */
    private Float allprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderall.state
     *
     * @mbg.generated Tue Jun 20 22:36:47 CST 2017
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderall.orderid
     *
     * @return the value of orderall.orderid
     *
     * @mbg.generated Tue Jun 20 22:36:47 CST 2017
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderall.orderid
     *
     * @param orderid the value for orderall.orderid
     *
     * @mbg.generated Tue Jun 20 22:36:47 CST 2017
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderall.userid
     *
     * @return the value of orderall.userid
     *
     * @mbg.generated Tue Jun 20 22:36:47 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderall.userid
     *
     * @param userid the value for orderall.userid
     *
     * @mbg.generated Tue Jun 20 22:36:47 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderall.allprice
     *
     * @return the value of orderall.allprice
     *
     * @mbg.generated Tue Jun 20 22:36:47 CST 2017
     */
    public Float getAllprice() {
        return allprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderall.allprice
     *
     * @param allprice the value for orderall.allprice
     *
     * @mbg.generated Tue Jun 20 22:36:47 CST 2017
     */
    public void setAllprice(Float allprice) {
        this.allprice = allprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderall.state
     *
     * @return the value of orderall.state
     *
     * @mbg.generated Tue Jun 20 22:36:47 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderall.state
     *
     * @param state the value for orderall.state
     *
     * @mbg.generated Tue Jun 20 22:36:47 CST 2017
     */
    public void setState(String state) {
        this.state = state;
    }
}