package com.database.mybatis.po;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.userid
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.psw
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private String psw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.realname
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private String realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.idcard
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private String idcard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.phone
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.address
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private String address;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.userid
	 * @return  the value of user.userid
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.userid
	 * @param userid  the value for user.userid
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
	 * @return  the value of user.name
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
	 * @param name  the value for user.name
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.psw
	 * @return  the value of user.psw
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public String getPsw() {
		return psw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.psw
	 * @param psw  the value for user.psw
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setPsw(String psw) {
		this.psw = psw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.realname
	 * @return  the value of user.realname
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.realname
	 * @param realname  the value for user.realname
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.idcard
	 * @return  the value of user.idcard
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public String getIdcard() {
		return idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.idcard
	 * @param idcard  the value for user.idcard
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.phone
	 * @return  the value of user.phone
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.phone
	 * @param phone  the value for user.phone
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.address
	 * @return  the value of user.address
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.address
	 * @param address  the value for user.address
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}
}