package com.database.mybatis.po;

public class Order {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.orderid
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	private String orderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.userid
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.allprice
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	private Float allprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.state
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	private String state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.orderid
	 * @return  the value of order.orderid
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	public String getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.orderid
	 * @param orderid  the value for order.orderid
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.userid
	 * @return  the value of order.userid
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.userid
	 * @param userid  the value for order.userid
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.allprice
	 * @return  the value of order.allprice
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	public Float getAllprice() {
		return allprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.allprice
	 * @param allprice  the value for order.allprice
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	public void setAllprice(Float allprice) {
		this.allprice = allprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.state
	 * @return  the value of order.state
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.state
	 * @param state  the value for order.state
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	public void setState(String state) {
		this.state = state;
	}
}