package com.database.mybatis.mapper;

import com.database.mybatis.po.Adminuser;
import com.database.mybatis.po.AdminuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminuserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminuser
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	long countByExample(AdminuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminuser
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int deleteByExample(AdminuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminuser
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminuser
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int insert(Adminuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminuser
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int insertSelective(Adminuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminuser
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	List<Adminuser> selectByExample(AdminuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminuser
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	Adminuser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminuser
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Adminuser record, @Param("example") AdminuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminuser
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int updateByExample(@Param("record") Adminuser record, @Param("example") AdminuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminuser
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int updateByPrimaryKeySelective(Adminuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminuser
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int updateByPrimaryKey(Adminuser record);
}