package com.database.mybatis.mapper;

import com.database.mybatis.po.Newspaper;
import com.database.mybatis.po.NewspaperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewspaperMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	long countByExample(NewspaperExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int deleteByExample(NewspaperExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int deleteByPrimaryKey(Integer newsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int insert(Newspaper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int insertSelective(Newspaper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	List<Newspaper> selectByExampleWithBLOBs(NewspaperExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	List<Newspaper> selectByExample(NewspaperExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	Newspaper selectByPrimaryKey(Integer newsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Newspaper record, @Param("example") NewspaperExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") Newspaper record, @Param("example") NewspaperExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int updateByExample(@Param("record") Newspaper record, @Param("example") NewspaperExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int updateByPrimaryKeySelective(Newspaper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(Newspaper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaper
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int updateByPrimaryKey(Newspaper record);
}