package com.database.mybatis.po;

public class Adminuser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuser.id
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuser.name
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuser.psw
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private String psw;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuser.id
	 * @return  the value of adminuser.id
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuser.id
	 * @param id  the value for adminuser.id
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuser.name
	 * @return  the value of adminuser.name
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuser.name
	 * @param name  the value for adminuser.name
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuser.psw
	 * @return  the value of adminuser.psw
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public String getPsw() {
		return psw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuser.psw
	 * @param psw  the value for adminuser.psw
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setPsw(String psw) {
		this.psw = psw;
	}
}