package com.database.mybatis.mapper;

import com.database.mybatis.po.Order;
import com.database.mybatis.po.OrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	long countByExample(OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	int deleteByExample(OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	int deleteByPrimaryKey(String orderid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	int insert(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	int insertSelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	List<Order> selectByExample(OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	Order selectByPrimaryKey(String orderid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	int updateByPrimaryKeySelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Tue Jun 20 22:18:23 CST 2017
	 */
	int updateByPrimaryKey(Order record);
}