package com.database.mybatis.po;

import java.util.ArrayList;
import java.util.List;

public class NewspaperclassExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public NewspaperclassExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andClassnumIsNull() {
			addCriterion("classnum is null");
			return (Criteria) this;
		}

		public Criteria andClassnumIsNotNull() {
			addCriterion("classnum is not null");
			return (Criteria) this;
		}

		public Criteria andClassnumEqualTo(Integer value) {
			addCriterion("classnum =", value, "classnum");
			return (Criteria) this;
		}

		public Criteria andClassnumNotEqualTo(Integer value) {
			addCriterion("classnum <>", value, "classnum");
			return (Criteria) this;
		}

		public Criteria andClassnumGreaterThan(Integer value) {
			addCriterion("classnum >", value, "classnum");
			return (Criteria) this;
		}

		public Criteria andClassnumGreaterThanOrEqualTo(Integer value) {
			addCriterion("classnum >=", value, "classnum");
			return (Criteria) this;
		}

		public Criteria andClassnumLessThan(Integer value) {
			addCriterion("classnum <", value, "classnum");
			return (Criteria) this;
		}

		public Criteria andClassnumLessThanOrEqualTo(Integer value) {
			addCriterion("classnum <=", value, "classnum");
			return (Criteria) this;
		}

		public Criteria andClassnumIn(List<Integer> values) {
			addCriterion("classnum in", values, "classnum");
			return (Criteria) this;
		}

		public Criteria andClassnumNotIn(List<Integer> values) {
			addCriterion("classnum not in", values, "classnum");
			return (Criteria) this;
		}

		public Criteria andClassnumBetween(Integer value1, Integer value2) {
			addCriterion("classnum between", value1, value2, "classnum");
			return (Criteria) this;
		}

		public Criteria andClassnumNotBetween(Integer value1, Integer value2) {
			addCriterion("classnum not between", value1, value2, "classnum");
			return (Criteria) this;
		}

		public Criteria andClassnameIsNull() {
			addCriterion("classname is null");
			return (Criteria) this;
		}

		public Criteria andClassnameIsNotNull() {
			addCriterion("classname is not null");
			return (Criteria) this;
		}

		public Criteria andClassnameEqualTo(String value) {
			addCriterion("classname =", value, "classname");
			return (Criteria) this;
		}

		public Criteria andClassnameNotEqualTo(String value) {
			addCriterion("classname <>", value, "classname");
			return (Criteria) this;
		}

		public Criteria andClassnameGreaterThan(String value) {
			addCriterion("classname >", value, "classname");
			return (Criteria) this;
		}

		public Criteria andClassnameGreaterThanOrEqualTo(String value) {
			addCriterion("classname >=", value, "classname");
			return (Criteria) this;
		}

		public Criteria andClassnameLessThan(String value) {
			addCriterion("classname <", value, "classname");
			return (Criteria) this;
		}

		public Criteria andClassnameLessThanOrEqualTo(String value) {
			addCriterion("classname <=", value, "classname");
			return (Criteria) this;
		}

		public Criteria andClassnameLike(String value) {
			addCriterion("classname like", value, "classname");
			return (Criteria) this;
		}

		public Criteria andClassnameNotLike(String value) {
			addCriterion("classname not like", value, "classname");
			return (Criteria) this;
		}

		public Criteria andClassnameIn(List<String> values) {
			addCriterion("classname in", values, "classname");
			return (Criteria) this;
		}

		public Criteria andClassnameNotIn(List<String> values) {
			addCriterion("classname not in", values, "classname");
			return (Criteria) this;
		}

		public Criteria andClassnameBetween(String value1, String value2) {
			addCriterion("classname between", value1, value2, "classname");
			return (Criteria) this;
		}

		public Criteria andClassnameNotBetween(String value1, String value2) {
			addCriterion("classname not between", value1, value2, "classname");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table newspaperclass
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 17 23:12:21 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}