package com.database.mybatis.mapper;

import com.database.mybatis.po.Newspaperclass;
import com.database.mybatis.po.NewspaperclassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewspaperclassMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	long countByExample(NewspaperclassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int deleteByExample(NewspaperclassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int deleteByPrimaryKey(Integer classnum);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int insert(Newspaperclass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int insertSelective(Newspaperclass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	List<Newspaperclass> selectByExample(NewspaperclassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	Newspaperclass selectByPrimaryKey(Integer classnum);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Newspaperclass record,
			@Param("example") NewspaperclassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int updateByExample(@Param("record") Newspaperclass record, @Param("example") NewspaperclassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int updateByPrimaryKeySelective(Newspaperclass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newspaperclass
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	int updateByPrimaryKey(Newspaperclass record);
}