package com.database.mybatis.po;

public class Newspaperclass {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newspaperclass.classnum
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private Integer classnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newspaperclass.classname
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	private String classname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newspaperclass.classnum
	 * @return  the value of newspaperclass.classnum
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public Integer getClassnum() {
		return classnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newspaperclass.classnum
	 * @param classnum  the value for newspaperclass.classnum
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setClassnum(Integer classnum) {
		this.classnum = classnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newspaperclass.classname
	 * @return  the value of newspaperclass.classname
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public String getClassname() {
		return classname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newspaperclass.classname
	 * @param classname  the value for newspaperclass.classname
	 * @mbg.generated  Tue Jun 20 22:36:47 CST 2017
	 */
	public void setClassname(String classname) {
		this.classname = classname;
	}
}